# Generated by Django 3.0.7 on 2020-06-17 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
