# Generated by Django 3.0.3 on 2020-06-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_list_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
